/**
 * Generates _web-assets.ts with embedded file imports for all web dist files.
 * Run after building the web SPA: `bun scripts/generate-web-assets.ts`
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, posix, relative } from 'node:path';

const WEB_DIST = join(import.meta.dir, '..', 'packages', 'web', 'dist');
const OUTPUT = join(
  import.meta.dir,
  '..',
  'packages',
  'server',
  'src',
  '_web-assets.ts',
);

function walk(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...walk(full));
    } else {
      results.push(full);
    }
  }
  return results;
}

const files = walk(WEB_DIST);
const imports: string[] = [];
const entries: string[] = [];

for (let i = 0; i < files.length; i++) {
  const abs = files[i];
  const rel = relative(WEB_DIST, abs);
  const urlPath = `/${posix.join(...rel.split('\\'))}`;
  const importPath = posix.join('../../web/dist', ...rel.split('\\'));
  const varName = `asset${i}`;

  imports.push(`import ${varName} from '${importPath}' with { type: 'file' };`);
  entries.push(`  '${urlPath}': ${varName},`);
}

const content = `// Auto-generated by scripts/generate-web-assets.ts — do not edit
${imports.join('\n')}

export const webAssets: Record<string, string> = {
${entries.join('\n')}
};
`;

writeFileSync(OUTPUT, content, 'utf-8');
console.log(`Generated ${OUTPUT} with ${files.length} embedded assets`);
