/**
 * Mapping of Azure DevOps built-in task names to their MS Learn documentation URL slugs.
 *
 * Source: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference
 *
 * The full doc URL is:
 *   https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/{slug}-v{version}
 *
 * This mapping exists because the heuristic PascalCase → kebab-case conversion
 * produces incorrect slugs for many tasks (e.g. PowerShell → "power-shell"
 * instead of "powershell").
 */
export const TASK_DOC_SLUGS: Record<string, string> = {
  // Build tasks
  DotNetCoreCLI: 'dotnet-core-cli',
  'AdvancedSecurity-Codeql-Init': 'advanced-security-codeql-init',
  'AdvancedSecurity-Codeql-Analyze': 'advanced-security-codeql-analyze',
  'AdvancedSecurity-Publish': 'advanced-security-publish',
  AndroidBuild: 'android-build',
  AndroidSigning: 'android-signing',
  Ant: 'ant',
  AzureIoTEdge: 'azure-iot-edge',
  CMake: 'cmake',
  ContainerBuild: 'container-build',
  Docker: 'docker',
  DockerCompose: 'docker-compose',
  DownloadGitHubNugetPackage: 'download-github-nuget-package',
  Go: 'go',
  Gradle: 'gradle',
  Grunt: 'grunt',
  gulp: 'gulp',
  PublishSymbols: 'publish-symbols',
  JenkinsQueueJob: 'jenkins-queue-job',
  Maven: 'maven',
  MSBuild: 'msbuild',
  SonarQubePrepare: 'sonar-qube-prepare',
  SonarQubePublish: 'sonar-qube-publish',
  SonarQubeAnalyze: 'sonar-qube-analyze',
  VSBuild: 'vsbuild',
  Xcode: 'xcode',
  XcodePackageiOS: 'xcode-package-ios',

  // Deploy tasks
  AppCenterDistribute: 'app-center-distribute',
  AzureResourceManagerTemplateDeployment: 'azure-resource-manager-template-deployment',
  AzureAppConfigurationExport: 'azure-app-configuration-export',
  AzureAppConfigurationImport: 'azure-app-configuration-import',
  AzureAppConfigurationSnapshot: 'azure-app-configuration-snapshot',
  AzureWebPowerShellDeployment: 'azure-web-powershell-deployment',
  AzureRmWebAppDeployment: 'azure-rm-web-app-deployment',
  AzureAppServiceManage: 'azure-app-service-manage',
  AzureAppServiceSettings: 'azure-app-service-settings',
  AzureCLI: 'azure-cli',
  AzureCloudPowerShellDeployment: 'azure-cloud-powershell-deployment',
  AzureContainerApps: 'azure-container-apps',
  AzureMysqlDeployment: 'azure-mysql-deployment',
  AzureFileCopy: 'azure-file-copy',
  AzureFunctionOnKubernetes: 'azure-function-on-kubernetes',
  AzureFunctionApp: 'azure-function-app',
  AzureFunctionAppContainer: 'azure-function-app-container',
  AzureKeyVault: 'azure-key-vault',
  AzureMonitorAlerts: 'azure-monitor-alerts',
  AzurePowerShell: 'azure-powershell',
  AzureResourceGroupDeployment: 'azure-resource-group-deployment',
  AzureSpringCloud: 'azure-spring-cloud',
  SqlAzureDacpacDeployment: 'sql-azure-dacpac-deployment',
  AzureVmssDeployment: 'azure-vmss-deployment',
  AzureWebApp: 'azure-web-app',
  AzureWebAppContainer: 'azure-web-app-container',
  PackerBuild: 'packer-build',
  AzurePolicyCheckGate: 'azure-policy-check-gate',
  Chef: 'chef',
  ChefKnife: 'chef-knife',
  CopyFilesOverSSH: 'copy-files-over-ssh',
  KubernetesManifest: 'kubernetes-manifest',
  IISWebAppDeploymentOnMachineGroup: 'iisweb-app-deployment-on-machine-group',
  IISWebAppDeployment: 'iisweb-app-deployment',
  IISWebAppManagementOnMachineGroup: 'iisweb-app-management-on-machine-group',
  InvokeRESTAPI: 'invoke-rest-api',
  Kubernetes: 'kubernetes',
  ManualIntervention: 'manual-intervention',
  ManualValidation: 'manual-validation',
  MysqlDeploymentOnMachineGroup: 'mysql-deployment-on-machine-group',
  HelmDeploy: 'helm-deploy',
  PowerShellOnTargetMachines: 'powershell-on-target-machines',
  ServiceFabricDeploy: 'service-fabric-deploy',
  ServiceFabricComposeDeploy: 'service-fabric-compose-deploy',
  SqlDacpacDeploymentOnMachineGroup: 'sql-dacpac-deployment-on-machine-group',
  SqlServerDacpacDeployment: 'sql-server-dacpac-deployment',
  SSH: 'ssh',
  WindowsMachineFileCopy: 'windows-machine-file-copy',

  // Package tasks
  CargoAuthenticate: 'cargo-authenticate',
  CocoaPods: 'cocoa-pods',
  CondaEnvironment: 'conda-environment',
  DownloadGithubNpmPackage: 'download-github-npm-package',
  MavenAuthenticate: 'maven-authenticate',
  Npm: 'npm',
  npmAuthenticate: 'npm-authenticate',
  NuGetCommand: 'nuget-command',
  NuGet: 'nuget',
  NuGetAuthenticate: 'nuget-authenticate',
  NuGetInstaller: 'nuget-installer',
  NuGetPackager: 'nuget-packager',
  NuGetPublisher: 'nuget-publisher',
  NuGetRestore: 'nuget-restore',
  PyPIPublisher: 'py-pi-publisher',
  PipAuthenticate: 'pip-authenticate',
  TwineAuthenticate: 'twine-authenticate',
  UniversalPackages: 'universal-packages',

  // Test tasks
  AppCenterTest: 'app-center-test',
  AzureLoadTest: 'azure-load-test',
  AzureTestPlan: 'azure-test-plan',
  ContainerStructureTest: 'container-structure-test',
  VSMobileCenterTest: 'vsmobile-center-test',
  PublishCodeCoverageResults: 'publish-code-coverage-results',
  PublishTestResults: 'publish-test-results',
  RunVisualStudioTestsusingTestAgent: 'run-visual-studio-testsusing-test-agent',
  VSTest: 'vstest',
  DeployVisualStudioTestAgent: 'deploy-visual-studio-test-agent',

  // Tool tasks
  DotNetCoreInstaller: 'dotnet-core-installer',
  DockerInstaller: 'docker-installer',
  DuffleInstaller: 'duffle-installer',
  GoTool: 'go-tool',
  HelmInstaller: 'helm-installer',
  FuncToolsInstaller: 'func-tools-installer',
  JavaToolInstaller: 'java-tool-installer',
  KubectlInstaller: 'kubectl-installer',
  KubeloginInstaller: 'kubelogin-installer',
  NuGetToolInstaller: 'nuget-tool-installer',
  UseDotNet: 'use-dotnet',
  UseNode: 'use-node',
  NodeTool: 'node-tool',
  UsePythonVersion: 'use-python-version',
  UseRubyVersion: 'use-ruby-version',
  VisualStudioTestPlatformInstaller: 'visual-studio-test-platform-installer',

  // Utility tasks
  'AdvancedSecurity-Dependency-Scanning': 'advanced-security-dependency-scanning',
  ArchiveFiles: 'archive-files',
  AzureNLBManagement: 'azure-nlb-management',
  Bash: 'bash',
  BatchScript: 'batch-script',
  Cache: 'cache',
  CacheBeta: 'cache-beta',
  CmdLine: 'cmd-line',
  CopyPublishBuildArtifacts: 'copy-publish-build-artifacts',
  CopyFiles: 'copy-files',
  cURLUploader: 'curl-uploader',
  DecryptFile: 'decrypt-file',
  Delay: 'delay',
  DeleteFiles: 'delete-files',
  AzureStaticWebApp: 'azure-static-web-app',
  DownloadFileshareArtifacts: 'download-fileshare-artifacts',
  DownloadBuildArtifacts: 'download-build-artifacts',
  DownloadGitHubRelease: 'download-github-release',
  DownloadPackage: 'download-package',
  DownloadPipelineArtifact: 'download-pipeline-artifact',
  DownloadSecureFile: 'download-secure-file',
  ExtractFiles: 'extract-files',
  FileTransform: 'file-transform',
  FtpUpload: 'ftp-upload',
  GitHubComment: 'github-comment',
  GitHubRelease: 'github-release',
  InstallAppleCertificate: 'install-apple-certificate',
  InstallAppleProvisioningProfile: 'install-apple-provisioning-profile',
  InstallSSHKey: 'install-ssh-key',
  AzureFunction: 'azure-function',
  JenkinsDownloadArtifacts: 'jenkins-download-artifacts',
  NodeTaskRunnerInstaller: 'node-task-runner-installer',
  Notation: 'notation',
  PowerShell: 'powershell',
  PublishBuildArtifacts: 'publish-build-artifacts',
  PublishPipelineArtifact: 'publish-pipeline-artifact',
  PublishPipelineMetadata: 'publish-pipeline-metadata',
  PublishToAzureServiceBus: 'publish-to-azure-service-bus',
  PythonScript: 'python-script',
  AzureMonitor: 'azure-monitor',
  queryWorkItems: 'query-work-items',
  ReviewApp: 'review-app',
  ServiceFabricPowerShell: 'service-fabric-powershell',
  ShellScript: 'shell-script',
  ServiceFabricUpdateAppVersions: 'service-fabric-update-app-versions',
  ServiceFabricUpdateManifests: 'service-fabric-update-manifests',
};
